# Generated by Django 2.1.11 on 2019-08-24 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Recipient', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('yearly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_reimbursements_accepted', models.IntegerField(default=0)),
                ('total_reimbursements_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('total_purchases_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_reimbursements_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='total_reimbursements_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='total_reimbursements_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Donor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Donor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Recipient'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Store'),
        ),
    ]
