# Generated by Django 2.1.11 on 2019-08-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20190824_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='location',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
