# Generated by Django 2.1.11 on 2019-08-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20190824_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='customerId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
