# Generated by Django 2.1.11 on 2019-08-25 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20190824_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='location',
        ),
        migrations.AddField(
            model_name='purchase',
            name='hash',
            field=models.CharField(default=uuid.UUID('7debe51a-c6e4-11e9-be62-54ee75d2b9cb'), max_length=64),
        ),
        migrations.AddField(
            model_name='recipient',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recipient',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
    ]
