# Generated by Django 2.1.11 on 2019-08-25 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20190824_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='hash',
        ),
        migrations.AddField(
            model_name='purchase',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d0f6c58c-c6f6-11e9-a1ca-38378bf0f823'), max_length=64),
        ),
    ]
